src_image_path: "/mnt/nas5/suhyeon/datasets/valAGE-Set"
edit_model_name: "sd-legacy/stable-diffusion-inpainting"
seed: 42
eval_size: 256
target_model: "omniguard" # ["omniguard", "wam", "stableguard]
save_path: "/mnt/nas5/suhyeon/projects/eval_spliceless/omniguard/512_valAGE_sd"
start_idx: 0

weight_paths:
  omniguard: "/mnt/nas5/suhyeon/checkpoints/omniguard/"
  wam: "/mnt/nas5/suhyeon/checkpoints/wam/"
  stableguard: "/mnt/nas5/suhyeon/checkpoints/stableguard/weights/clean"
  ours: ""

normalization: # related to their own embedder
  omniguard: "rescale"
  wam: "imagenet" # TODO: try "imagenet"
  stableguard: "rescale"
  ours: "rescale" # doesn't matter

num_bits:
  omniguard: 64
  wam: 32
  stableguard: 48
  ours: 0

train_img_size:
  omniguard: 512
  wam: 256
  stableguard: 256
  ours: 256